# Generated by Django 5.0.7 on 2024-07-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(blank=True, max_length=255, null=True)),
                ('email', models.TextField(blank=True, max_length=30)),
            ],
        ),
    ]
